### ISSUE TITLE
Question: How to use session cookie to authenticate other requests?

### ISSUE THREAD

**Issue by jekelija** [kaj/warp-diesel-ructe-sample#2]
Love this demo, thank you so much for doing this. Was trying to understand how the session cookie authenticates other requests? If i want an endpoint to fail with a 403 without the session cookie, how would i do so?

**Comment by kaj** [comment]
Hi!

The session key is verified by the session filter, defined in `session.rs` as:

https://github.com/kaj/warp-diesel-ructe-sample/blob/d58930d92583b344d50036e9930e5a4da04e6f5b/src/session.rs#L123-L139

Lines 126 and 129 gets the key from the cookie, and line 131 creates a session from a database pool and that session.  The `Session::from_key` constructor method earlier in the same file looks up the key in the database and sets the user in a session variable.

The session filter is the injected in the routing mechanism by the `s()` alias function, created in `main` like this:

https://github.com/kaj/warp-diesel-ructe-sample/blob/d58930d92583b344d50036e9930e5a4da04e6f5b/src/main.rs#L32-L36


The simplest way to require a logged in user in a handler is to explicitly check at the start of handler, something like:

```rust
fn private_page(session: Session) -> Result<impl Reply, Rejection> {
    if session.user().is_none() {
        return Err(permission_denied());
    }
    // ... rest of the handler ...
}
```
... where `permission_denied()` returns a suitable rejection.

If there is lots of handlers that require authentication, it might be nicer to do that check already in the route handler.  That can be done by wrapping the `s()` session initializser in something that rejects if there is no authenticated user.

I'm rather busy this weekend, I hope this quick writeup is any help to you, but I'll also try to get back later and add some more examples of this, and maybe touch up some other parts of this code.

You can also look at a more "real" example in https://github.com/kaj/rphotos , the session handler (and especially database pool initialization) code there is probably a lot better than this example, but then also hidden among a lot more application code.

**Comment by jekelija** [comment]
That makes a lot of sense, thank you!
