### ISSUE TITLE
Update warp to "0.2.3"

### ISSUE THREAD

**Issue by zwhitchcox** [kaj/warp-diesel-ructe-sample#3]
Hi, I am attempting to adapt your code into my own code base, but it occurs to me that there are quite a few errors when I try to just copy and paste your code.

I cloned your codebase, and there were 24 errors. For example, when I tried to copy the [create_session]((https://github.com/kaj/warp-diesel-ructe-sample/blob/master/src/session.rs#L123) function, it gave me an error:

```
the trait bound `std::result::Result<session::Session, warp::reject::Rejection>: core::future::future::Future` is not satisfied
    
the trait `core::future::future::Future` is not implemented for `std::result::Result<session::Session, warp::reject::Rejection>`
    
note: required because of the requirements on the impl of `futures_core::future::TryFuture` for `std::result::Result<session::Session, warp::reject::Rejection>`rustc(E0277)
session.rs(138, 10): the trait `core::future::future::Future` is not implemented for `std::result::Result<session::Session, warp::reject::Rejection>`
```

So, I made the closure have an async block:

```rust
            .and_then(move |key: Option<String>| async {
                let pool = pool.clone();
                let key = key.as_ref().map(|s| &**s);

                match pool.get() {
                    Ok(conn) => Ok(Session::from_key(conn, key)),
                    Err(e) => {
                        error!("Failed to get a db connection");
                        Err(warp::reject::not_found())
                    }
                }
            })
            .boxed()
```

but that gave me the error:

```
    lifetime may not live long enough
    
    returning this value requires that `'1` must outlive `'2`
    
    note: closure implements `Fn`, so references to captured variables can't escape the closurerustc
    session.rs(138, 19): lifetime `'1` represents this closure's body
    session.rs(138, 44): return type of closure is impl core::future::future::Future
    session.rs(138, 46): returning this value requires that `'1` must outlive `'2`
```

And so on, as I keep fixing them, it seems like it just makes more...

the point being, I am very grateful that you put this out there, as it has already helped me a ton, but it would be even more useful if you could upgrade the warp version, and possibly other dependencies so people could just copy and paste your code without having to deal with all the errors.

thank you for contributing to open source!

**Comment by zwhitchcox** [comment]
By the way, I'm not sure if you realize this, but you're still the top result when you google "warp diesel rust example"

**Comment by kaj** [comment]
> By the way, I'm not sure if you realize this, but you're still the top result when you google "warp diesel rust example"

Oh.  I guess I really should fix it then.  :-)  I have other projects where I up-to-date warp, so I should be able to fix it in  a day or two.

**Comment by zwhitchcox** [comment]
you da man

**Comment by zwhitchcox** [comment]
So, I was able to fix the issue in the comment with this code:

```rs
pub fn create_session_filter(db_url: &str) -> BoxedFilter<(Session,)> {
    let pool = pg_pool(db_url);
    warp::any()
        .and(cookie::optional("NORMAL_AUTH"))
        .and_then(move |key: Option<String>| {
            let pool = pool.clone();
            async move {
                let key = key.as_ref().map(|s| &**s);
                match pool.get() {
                    Ok(conn) => Ok(Session::from_key(conn, key)),
                    Err(e) => {
                        error!("Failed to get a db connection");
                        Err(warp::reject::not_found())
                    }
                }
            })
        .boxed()
}
```

Just in case that helps with the update...it was fairly hard to figure that out lol
